### PR TITLE
Use kernel internal function for flushing the TLB

### PR DESCRIPTION
**Pull request by cc0x1f**
With this change, the module now uses the kernel internal function for flushing the TLB instead of the custom function. In my tests, this change did not introduce any problems in the provided demos. I also benchmarked the difference in cycles required for these two methods and the results show a clear improvement:

PTEditor TLB invalidation: 2008741
Kernel TLB invalidation: 378
Sample size: 10000

I also added a compile time switch so that the previous function can be used instead of the kernel internal function. The switch is documented in the README file.

We might want to consider using a runtime switch instead of a compile-time switch, even though this adds a little bit of overhead for every TLB flush.

### CODE REVIEW

**Comment by misc0110** [comment]
Does this invalidate the TLB on all CPUs?

Using a function pointer pointing to the flush function should not introduce a lot of overhead.

**Comment by cc0x1f** [comment]
Based on the source code of the kernel function this should invalidate the TLB on all CPUs if it is necessary.

**Comment by cc0x1f** [comment]
The patch now uses a runtime instead of a compile-time switch.

**Comment by misc0110** [comment]
Looks good. Can you add your tests to the unit tests as well?

**Comment by cc0x1f** [comment]
I added some unit tests.

**Pull request merged**
